apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tiered-storage-nfs
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 990Gi
  storageClassName: nfs